num_steps: 10000000
batch_size: 256
latent_batch_size: 32
num_sequences: 8
lr: 0.0003
latent_lr: 0.0001
feature_dim: 512  # 256
latent1_dim: 64  # 32
latent2_dim: 512  # 256
hidden_units: [256, 256]
memory_size: 1000000
gamma: 0.99
tau: 0.005
target_entropy_ratio: 0.98
leaky_slope: 0.2
start_steps: 50000
initial_learning_steps: 100000
update_interval: 1
log_interval: 100
eval_interval: 50000
num_eval_steps: 50000
max_episode_steps: 50000
grad_cliping: